spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.h2.console.enabled: true
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password: password

camunda.bpm.admin-user:
  id: admin
  password: admin

#kafka:
#  bootstrapAddress: 'localhost:9092'